### ISSUE TITLE
Functionality: can not signup with username and password

### ISSUE THREAD

**Issue by Supakrit65** [jaybjackie/HungryMe#101]
![Screenshot 2022-11-23 103114](https://user-images.githubusercontent.com/92836314/203464299-31576d68-ab73-40a8-b107-bb5d3506cd4b.png)
![Screenshot 2022-11-23 103659](https://user-images.githubusercontent.com/92836314/203464727-e1be69e4-5659-4c5a-aca6-3e72dca339f9.png)

**Comment by jaybjackie** [comment]
Due to register form problem, I decided to change authentication system to use Google OAuth only.
![image](https://user-images.githubusercontent.com/88821578/204577286-9c490389-b759-4063-b2f9-592a3543ffda.png)
https://jaybjackie.pythonanywhere.com
