### ISSUE TITLE
Functionality: 403 Forbidden occurs when sending comments.

### ISSUE THREAD

**Issue by Tanabodee-Yambangyang** [jaybjackie/HungryMe#104]
![Screenshot 2022-11-23 105706](https://user-images.githubusercontent.com/92779764/203466560-39df860b-1766-48f3-ac04-dff3afb33835.png)

![Screenshot 2022-11-23 104030](https://user-images.githubusercontent.com/92779764/203466451-e33ace32-a803-4929-bd64-4c2624d3fbc3.png)

**Comment by zevenfox** [comment]
already fix this.
