### ISSUE TITLE
Functionality: Problems with search menu

### ISSUE THREAD

**Issue by teenteennnii** [jaybjackie/HungryMe#105]
In the search menu, user cannot search with some words even though I see the menu on main page. (For example word "cake" did not find anything, but "pie" found results)

For main page:
<img width="1381" alt="Screenshot 2565-11-23 at 11 16 09" src="https://user-images.githubusercontent.com/92800086/203468326-146ceeee-d38f-430a-a8b8-f4fe6e4d46d6.png">

For "Cake":
<img width="1440" alt="Screenshot 2565-11-23 at 11 11 03" src="https://user-images.githubusercontent.com/92800086/203468050-4c29b9c6-8098-4375-8d36-bbd92ad228c9.png">

For "Pie"
<img width="1440" alt="Screenshot 2565-11-23 at 11 11 21" src="https://user-images.githubusercontent.com/92800086/203468054-63f32eb4-2bd5-4ef5-b357-85f768a63b1d.png">

**Comment by zevenfox** [comment]
We have this issue already. It is  https://github.com/jaybjackie/HungryMe/issues/87.
