### ISSUE TITLE
Error page occurs when clicking Create Menu button.

### ISSUE THREAD

**Issue by Tanabodee-Yambangyang** [jaybjackie/HungryMe#111]
### I tried clicking the create menu button without typing any information and the error page occurred.
<br>

![Screenshot 2022-11-27 005418](https://user-images.githubusercontent.com/92779764/204102409-f0c6f7f9-ae79-4b46-9ec5-55a67d4326d7.png)

![Screenshot 2022-11-27 005438](https://user-images.githubusercontent.com/92779764/204102412-d1639fbd-294b-4d03-bc8e-3fa1c9dd195b.png)

**Comment by jaybjackie** [comment]
We fixed it. Now, it not allowed user to create food without filling the any information.
![image](https://user-images.githubusercontent.com/88821578/206388138-a4b6f8f3-5e76-4f79-8b68-6e4066021f11.png)
