### ISSUE TITLE
When I put long description. It not align by the box in create menu page.

### ISSUE THREAD

**Issue by MarojT** [jaybjackie/HungryMe#113]
![image](https://user-images.githubusercontent.com/59698469/204120132-3751cd82-903c-4e0a-b4ae-afbf8fca1a7f.png)

**Comment by jaybjackie** [comment]
We handle it.
![image](https://user-images.githubusercontent.com/88821578/206390499-d9ecd5e4-159c-4a9a-85e1-8bcf291eb28c.png)

Also fixed #114
