### ISSUE TITLE
In calories should not allow user input string.

### ISSUE THREAD

**Issue by MarojT** [jaybjackie/HungryMe#116]
![image](https://user-images.githubusercontent.com/59698469/204120572-29af239c-491a-439d-a5d5-01d6274f6088.png)

**Comment by MarojT** [comment]
![image](https://user-images.githubusercontent.com/59698469/204120633-492beb9b-7030-4d99-a900-88129f1de8b5.png)
 and then it goes error

**Comment by jaybjackie** [comment]
When user type string type in nutritions section, it is allowed. But we are not allowed to create the food and alert user to `enter a number`
![image](https://user-images.githubusercontent.com/88821578/206390938-3bb3453c-f525-4f31-b62f-419b13eeecf5.png)
