### ISSUE TITLE
Display block of menus on Homepage

### ISSUE THREAD

**Issue by jaybjackie** [jaybjackie/HungryMe#3]

**Comment by jaybjackie** [comment]
@Unikorn996 Any Problem Here? Is your task doing fine?

**Comment by jaybjackie** [comment]
Here is the other way to put text and image together as a block.
[https://www.youtube.com/watch?v=42Cvtx7TPDQ](https://www.youtube.com/watch?v=42Cvtx7TPDQ)

And you can decorate using css to make it look like Menu block we have design.

**Comment by jaybjackie** [comment]
As you may know, use `href`. So, when user click it. It will link to the specified path.

**Comment by Unikorn996** [comment]
finished
