### ISSUE TITLE
Show suggested food(with filter)

### ISSUE THREAD

**Issue by jaybjackie** [jaybjackie/HungryMe#35]
filterer by the following:
- [ ] **doesn't want** ingredients to be in the menu
- [ ] allergy 
- [ ] rating by user
- [ ] calories
- [ ] diets such as Vegetarian(No meat, No eggs), Vegetarian(No meat, No dairy)m Vegan, Ketogenic.
- [ ] cooking skill such as Beginner, Intermediate, Advance.
- [ ] cuisines such as American, Kid-friendly, Italian, Thai, Southern & soul food.

**Comment by Unikorn996** [comment]
FYI:
- Vegetarian -> No meat, No poultry, No fish
- Vegan -> No meat, No poultry, No fish, No dairy, No products from animals such as honey
For easier comprehension, vegan is just a little stricter than vegetarian. Just in case na ja.

**Comment by zevenfox** [comment]
From now on I will do these function and cut some function off.
- [ ] **doesn't want** ingredients to be in the menu : **Fish, Shrimp, meat etc.**
   - This will include diets such as Vegetarian(No meat, No eggs), Vegetarian(No meat, No dairy)m Vegan, Ketogenic.
- [ ] allergy : **Wheat, Dairy, Peanut, Egg, Seafood**
- [ ] calories : **High, Medium, Low**
- [ ] cooking skill : **Beginner, Intermediate, Advance.**
- [ ] rating by user [***optional function***]

**Comment by zevenfox** [comment]
> FYI:
> 
> * Vegetarian -> No meat, No poultry, No fish
> * Vegan -> No meat, No poultry, No fish, No dairy, No products from animals such as honey
> 
> For easier comprehension, vegan is just the vegetarian with a little stricter rules. Just in case na ja.

I think we will cut off this function for better user experience and add it to "doesn't want ingredients to be in the menu" function.

**Comment by zevenfox** [comment]
DONE!
