### ISSUE TITLE
Conflicting LOGIN_DIRECT_URL and LOGOUT_DIRECT_URL in settings.py

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#65]
In mysite/settings.py you have LOGIN_DIRECT_URL and LOGOUT_REDIRECT_URL
assigned twice, to different values.

**Comment by jaybjackie** [comment]
`LOGIN_REDIRECT_URL` remain the same but I change the other one to `LOGOUT_REDIRECT_URL = '/accounts/login/'`.
#79
