### ISSUE TITLE
Duplicate url pattern in settings/urls.py

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#66]
https://github.com/jaybjackie/HungryMe/blob/11fd684cd754a1dc6cd373a833353d85112fb54d/mysite/urls.py#L9-L10

Each url pattern should be mapped only once.

**Comment by jaybjackie** [comment]
I use `path('foods/', RedirectView.as_view(url="/"))` to redirect to the same place but b  precise more than the old way.

**Comment by jaybjackie** [comment]
I use the way of changing url of google auth. So, accounts/ will not messed together in the future.
