### ISSUE TITLE
Mapping multiple urls same app looks hacky

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#67]
https://github.com/jaybjackie/HungryMe/blob/11fd684cd754a1dc6cd373a833353d85112fb54d/mysite/urls.py#L6-L7

You are mapping both /* and /foods/* to the foods app.
You should carefully test that this does not create any subtle problems.
For example, does reverse URL lookup using Django `reverse("app:name")` work correctly?

If the only URL you need to redirect is "/" there are more precise ways
to do that, as in KU Polls Iteration 2.  We found at least 3 solutions that
don't require using "include".

**Comment by jaybjackie** [comment]
I use `path('foods/', RedirectView.as_view(url="/"))` instead of duplicate url pattern.
