### ISSUE TITLE
Errors in installation instructions

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#77]
1. The .env file usually goes in the project base directory, not in mysite.
2. Incorrect syntax for ALLOWED_HOSTS.  It should be a single string of comma separated values.
3. You don't import any data so the app cannot be used!
4.

**Comment by jaybjackie** [comment]
I will have a look and fix it ASAP(it think tonight).

**Comment by jaybjackie** [comment]
I have modify the Instructions in `README.md` file already. Anyway if there are any change in the future I will keep updating it.
