### ISSUE TITLE
Not externalizing settings

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#82]
https://github.com/jaybjackie/HungryMe/blob/e0e906064b8e137038af5c62f2796c407049eeaa/mysite/settings.py#L22-L29

You have not externalized ALLOWED_HOSTS, DEBUG, and the config for SECRET_KEY has an unnecessary cast.
There is no reason *not* to externalize these settings.

You should also externalize the database url and use dj-database-url to parse it.
You'll need that when you start to deploy.

**Comment by jaybjackie** [comment]
In process of deployment on pythonanywhere, I have externalize configuration in term of deploy the web on the internet.

**Comment by jbrucker** [comment]
You closed Issue #82 but you didn't fix it.

Since this is a "best practice" is software development and you already
learned how to do it, your project score will be penalized for this.

**Comment by jaybjackie** [comment]
> You closed Issue #82 but you didn't fix it. Since this is a "best practice" is software development and you already learned how to do it, your project score will be penalized for this.
> […](#)

My bad I careless think that config in deployment stage is enough. 
I will make it right.

**Comment by jaybjackie** [comment]
Badly, I tried many ways to externalize all 3 variables. But, when debug is False I cannot externalize the ALLOWED_HOSTS.
So, I externalize DEBUG and SECRET_KEY only.
