### ISSUE TITLE
Google OAuth parameters

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#85]
https://github.com/jaybjackie/HungryMe/blob/61e27ffc9b70545fc0dcd06f814da612de66be77/mysite/settings.py#L146-L148

Read this allauth documentation about Google and the meaning of the `access-type` parameter:

https://django-allauth.readthedocs.io/en/latest/providers.html#google

**Comment by jaybjackie** [comment]
Thank you. I have read it and I will implementing it .
