### ISSUE TITLE
This app’s request is invalid.

### ISSUE THREAD

**Issue by dzptahh** [jaybjackie/HungryMe#99]
I can not login via Google.
- Error 400: redirect_uri_mismatch
- 
<img width="1440" alt="ภาพถ่ายหน้าจอ 2565-11-23 เวลา 10 03 16" src="https://user-images.githubusercontent.com/92835393/203462088-dd8ae313-140c-4201-9f6e-a69007a829fb.png">

**Comment by jaybjackie** [comment]
I fixed this bug already. Please have a try again.
PS. I will take some time to load the page in the first time because of fetching data from API.
[https://jaybjackie.pythonanywhere.com/](https://jaybjackie.pythonanywhere.com/)

**Comment by dzptahh** [comment]
**Awesome! I can logged in with google now 👍**
